# Generated by Django 3.2 on 2021-05-19 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210520_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartctl',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.device'),
        ),
    ]
