# Generated by Django 3.2 on 2021-05-28 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_smartctl_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartctl',
            name='Date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
