# Generated by Django 3.2 on 2021-05-19 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smart',
            name='device',
        ),
    ]
