# Generated by Django 3.2 on 2021-05-30 00:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_smartctl_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartctl',
            name='Current',
        ),
        migrations.RemoveField(
            model_name='smartctl',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='smartctl',
            name='RawValue',
        ),
        migrations.RemoveField(
            model_name='smartctl',
            name='Type',
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('Current', models.CharField(help_text='Current', max_length=30, null=True)),
                ('Type', models.CharField(help_text='Type', max_length=30, null=True)),
                ('RawValue', models.CharField(help_text='RawValue', max_length=30, null=True)),
                ('smartctl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.smartctl')),
            ],
        ),
    ]
